/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_procedure_keyderivation_KeyDerivationNative */

#ifndef _Included_com_example_procedure_keyderivation_KeyDerivationNative
#define _Included_com_example_procedure_keyderivation_KeyDerivationNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    kseafFromKausf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_kseafFromKausf
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    kamfFromKseaf
 * Signature: (Ljava/lang/String;[BLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_kamfFromKseaf
  (JNIEnv *, jclass, jstring, jbyteArray, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    algorithmKeyDerivation
 * Signature: (IILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_algorithmKeyDerivation
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    kgnbFromKamf
 * Signature: (JILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_kgnbFromKamf
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    nhFromKamf
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_nhFromKamf
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    kngRanStarFromKgnb
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_kngRanStarFromKgnb
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_example_procedure_keyderivation_KeyDerivationNative
 * Method:    kamfFromKamf
 * Signature: (IJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_procedure_keyderivation_KeyDerivationNative_kamfFromKamf
  (JNIEnv *, jclass, jint, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
