package com.example.procedure.infrastructure.wireshark;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Prepares the local Wireshark profile files required by tshark decoding.
 */
@Component
public class WiresharkProfileInitializer {

    private static final Logger log = LoggerFactory.getLogger(WiresharkProfileInitializer.class);

    private final WiresharkProperties props;

    public WiresharkProfileInitializer(WiresharkProperties props) {
        this.props = props;
    }

    @PostConstruct
    public void init() throws IOException {
        Path configRoot = props.activeConfigDirPathOrNull();
        if (configRoot == null) {
            log.info("Wireshark profile initialization skipped because no config directory is active.");
            return;
        }

        Path profileDir = configRoot.resolve("profiles").resolve(props.getProfileName());
        Files.createDirectories(profileDir);

        Path userDltsFile = profileDir.resolve("user_dlts");
        List<String> lines = new ArrayList<>();
        lines.add("# This file is automatically generated, DO NOT MODIFY.");

        Map<Integer, String> map = props.getUserDlts();
        if (map == null || map.isEmpty()) {
            log.warn("wireshark.userDlts is empty; fallback to 147 -> nr-rrc.ul.dcch");
            lines.add(toUatLine(147, "nr-rrc.ul.dcch"));
        } else {
            map.entrySet().stream()
                    .sorted(Map.Entry.comparingByKey())
                    .forEach(e -> {
                        Integer dlt = e.getKey();
                        String dissector = e.getValue();
                        if (dlt == null || dissector == null || dissector.isBlank()) {
                            return;
                        }
                        lines.add(toUatLine(dlt, dissector.trim()));
                    });
        }

        atomicWrite(userDltsFile, lines);

        log.info(
                "Wireshark profile ready. configDir={}, profileName={}, user_dlts={}",
                configRoot,
                props.getProfileName(),
                userDltsFile
        );
    }

    private static String toUatLine(int dlt, String dissector) {
        int userIdx = dlt - 147;
        String userLabel = "User " + userIdx + " (DLT=" + dlt + ")";
        return "\"" + userLabel + "\",\"" + dissector + "\",\"0\",\"\",\"0\",\"\"";
    }

    private static void atomicWrite(Path target, List<String> lines) throws IOException {
        Files.createDirectories(target.getParent());
        Path tmp = target.resolveSibling(target.getFileName().toString() + ".tmp");
        Files.write(
                tmp,
                lines,
                StandardCharsets.US_ASCII,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING
        );
        Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
    }
}
