package com.example.procedure.wireshark;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

@Component
public class WiresharkProfileInitializer {

    private static final Logger log = LoggerFactory.getLogger(WiresharkProfileInitializer.class);

    private final WiresharkProperties props;

    public WiresharkProfileInitializer(WiresharkProperties props) {
        this.props = props;
    }

    @PostConstruct
    public void init() throws IOException {
        Path cfgRoot = props.cfgRootPath();
        Path profileDir = cfgRoot.resolve("profiles").resolve(props.getProfileName());
        Files.createDirectories(profileDir);

        Path userDltsFile = profileDir.resolve("user_dlts");

        // 生成你已经验证能被 tshark 读取的 UAT 风格 user_dlts
        // 格式示例：
        // # This file is automatically generated, DO NOT MODIFY.
        // "User 0 (DLT=147)","nr-rrc.ul.dcch","0","","0",""
        List<String> lines = new ArrayList<>();
        lines.add("# This file is automatically generated, DO NOT MODIFY.");

        Map<Integer, String> map = props.getUserDlts();
        if (map == null || map.isEmpty()) {
            // fallback（避免空配置导致没法跑）
            log.warn("wireshark.userDlts is empty; fallback to 147 -> nr-rrc.ul.dcch");
            lines.add(toUatLine(147, "nr-rrc.ul.dcch"));
        } else {
            // 保持稳定顺序：按 DLT 排序输出
            map.entrySet().stream()
                    .sorted(Map.Entry.comparingByKey())
                    .forEach(e -> {
                        Integer dlt = e.getKey();
                        String dissector = e.getValue();
                        if (dlt == null || dissector == null || dissector.isBlank()) return;
                        lines.add(toUatLine(dlt, dissector.trim()));
                    });
        }

        atomicWrite(userDltsFile, lines);

        log.info("Wireshark profile ready. cfgRoot={}, profileName={}, user_dlts={}",
                cfgRoot, props.getProfileName(), userDltsFile);
    }

    private static String toUatLine(int dlt, String dissector) {
        // DLT 147 -> User 0, 148 -> User 1 ... 162 -> User 15
        int userIdx = dlt - 147;
        String userLabel = "User " + userIdx + " (DLT=" + dlt + ")";
        // 注意：第三列这里用 "0"（带引号），其余空列保持 ""，与您贴的格式一致
        return "\"" + userLabel + "\",\"" + dissector + "\",\"0\",\"\",\"0\",\"\"";
    }

    private static void atomicWrite(Path target, List<String> lines) throws IOException {
        Files.createDirectories(target.getParent());
        Path tmp = target.resolveSibling(target.getFileName().toString() + ".tmp");
        Files.write(tmp, lines, StandardCharsets.US_ASCII,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.ATOMIC_MOVE);
    }
}
